useTabs: false,
tabWidth: 2,
singleQuote: true,
semi: false,
arrowParens: 'avoid',
trailingComma: 'es5',
htmlWhitespaceSensitivity: 'css',
endOfLine: 'lf'
overrides:
  - files:
      - '**/*.html'
    options:
      tabWidth: 4
